openapi: 3.0.3
info:
  title: Health API
  version: 1.0.0

# 健康检查 API

paths:
  /health:
    get:
      tags: [Health]
      operationId: health
      summary: 健康检查
      responses:
        '200':
          description: 服务正常
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/HealthResponse'
